### ISSUE TITLE
[Feature] Notification Manager Router and Silence

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/notification-manager#119]
Currently, the notification manager uses the namespace of alert to determine which receivers the alert needs to be sent to, users cannot manually specify.

The router is used to specify which alerts need to be sent to which receivers. The router can enrich the notification strategy of the notification manager.

Silences are a straightforward way to simply mute alerts for a given time. 

<img width="891" alt="1645683875(1)" src="https://user-images.githubusercontent.com/53003665/155469761-8c2a9b13-3751-4fad-8bf4-6d733b2de4ad.png">

The Silence CRD maybe this.

```
apiVersion: notification.kubesphere.io/v2beta2
kind: Silences
metadata:
  name: silences
  labels: 
     type: global
spec:
  enabled: true
  alertSelector:
    matchLabels:
      alerttype: auditing
  startsAt: "2022-02-23T01:15:20Z"
  schedule: "30 * * * *"
  duration: 30m
```

>If the duration is not set, the silences can be used as a global filter.

The Router CRD maybe this.

```
apiVersion: notification.kubesphere.io/v2beta3
kind: Router
metadata:
  name: router
spec:
  enabled: true
  matcher:
    matchLabels:
      alerttype: auditing
  receivers:  
    type: wechat
    name:
      - receiver1
      - receiver2
    regexName: ""
    selector:
      matchLabels:
        tenant: admin
```

Changes in NotificationManger CRD

```
apiVersion: notification.kubesphere.io/v2beta2
kind: NotificationManager
metadata:
  name: notification-manager
spec:
  batchMaxWait: 1m
  batchMaxSize: 100
  groupLabels:
  - namespace
  - alertname
  routePolicy: All
```

The `batchMaxWait` and `batchMaxSize` used to define how to pull alerts from the store.
The `groupLabels` is used to group alerts.
The `routePolicy` determines how to find receivers that notifications will be sent to, known values are RouterFirst and RouterOnly.
All: The alerts will send to the receivers which match the router, and the receivers of tenants who can access the namespace that the alert is in.
RouterFirst: The alerts will send to the receivers which match the router first, if no receiver is found, it will send to the receivers of tenants who can access the namespace that the alert is in.
RouterOnly: The alerts will send to the receivers which match the router only.
