### ISSUE TITLE
Receiver resource not recognized

### ISSUE THREAD

**Issue by DesistDaydream** [kubesphere/notification-manager#137]
```yaml
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-receiver
  labels:
    type: global
spec:
  dingtalk:
    chatbot:
      webhook:
        value: "https://oapi.dingtalk.com/robot/send?XXXXXXXXXX"
      keywords:
        - kubesphere
    enabled: true
    template: nm.default.markdown
    titleTemplate: nm.default.subject
    tmplType: markdown
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
```

Simulate alerts with curl
```bash
curl -XPOST http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts \
  -d '{"alerts":[{"status":"firing","labels":{"alertname":"KubePodCrashLooping","container":"busybox-3jb7u6","instance":"10.233.71.230:8080","job":"kube-state-metrics",
"namespace":"pp1","pod":"dd1-0","prometheus":"kubesphere-monitoring-system/k8s","severity":"critical"},"annotations":{"message":"Pod pp1/dd1-0 (busybox-3jb7u6) is restarting 1.07 times / 5 minutes."},"startsAt":"2020-02-26T07:05:04.989876849Z","endsAt":"0001-01-01T00
:00:00Z"}]}'
```
notification-manager logs
![image](https://user-images.githubusercontent.com/39847025/167282228-c0c8063f-c21c-47bc-b194-d3229c09916f.png)

Only received the following information
![image](https://user-images.githubusercontent.com/39847025/167282160-2791de7a-1cb7-48f6-ad0a-2250ba8bcf28.png)

This phenomenon seems to be that notification-manager does not use the specified template when processing the request sent by my Receiver

**Comment by DesistDaydream** [comment]
After split. Only `nm.default.markdown` is left for the `message` variable. Is there something wrong with this configuration?

![c5573d8f41b461733a3661e2c86dea7](https://user-images.githubusercontent.com/39847025/167539186-0a963bd9-0cc1-4ded-b99b-e589b189360d.jpg)

**Comment by wanjunlei** [comment]
Please provide the content of configmap `notification-manager-template`.

**Comment by DesistDaydream** [comment]
> Please provide the content of configmap `notification-manager-template`.

https://github.com/kubesphere/notification-manager/releases/download/v2.0.0/notification_manager.yaml

**Comment by wanjunlei** [comment]
Change the `spec,dingtalk.template` to `{{ template "nm.default.markdown" }}`, and try it again.

We will release 2.0.1 soon, which will fix this bug.

**Comment by DesistDaydream** [comment]
> Change the `spec,dingtalk.template` to `{{ template "nm.default.markdown" }}`, and try it again.
> 
> We will release 2.0.1 soon, which will fix this bug.

you mean like the following?
```yaml
  dingtalk:
    chatbot:
      atAll: true
      webhook:
        value: "https://oapi.dingtalk.com/robot/send?access_token=XXXX"
    enabled: true
    template: '{{ template "nm.default.markdown" }}'
    titleTemplate: nm.default.subject
    tmplType: markdown
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
      key: "template.go.tmpl"
```
