### ISSUE TITLE
Send the received alerts from different AlertManager'receiver as different notification-manager'receiver respectively

### ISSUE THREAD

**Issue by DesistDaydream** [kubesphere/notification-manager#142]
If the alertmanager is configured as follows
```yaml
receivers:
  - name: "ops"
    webhook_configs:
      - url: "http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts"
        send_resolved: true
  - name: "dev"
    webhook_configs:
      - url: "http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts"
```
How notification-manager handles the alerts of different AlertManager'receivers with different receivers.notification.kubesphere.io.

**Comment by wanjunlei** [comment]
Alerts sent to the same alertmanager receiver have the same label defined in the router match.

```
"routes":
  - "match":
      "alertname": "Watchdog"
    "receiver": "Watchdog"
  - "group_interval": "30s"
    "match":
      "alerttype": "event"
    "receiver": "event"
  - "group_interval": "30s"
    "match":
      "alerttype": "auditing"
    "receiver": "auditing"
  - "match_re":
      "alerttype": ".*"
    "receiver": "prometheus"
```

Notification Manager can handle alerts from different alertmanager receivers with different receivers by setting the alert selector like this.

```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: user1
  labels:
    app: notification-manager
    type: tenant
    user: user1
spec:
  email:
    alertSelector:
      matchExpressions:
      - key: alerttype
        operator: In
        value:
        - event
    to:
    - admin@gmail.com
```

Or, use a router in v2.0+.

```
apiVersion: notification.kubesphere.io/v2beta2
kind: Router
metadata:
  name: router1
spec:
  alertSelector:
    matchExpressions:
      - key: alerttype
        operator: In
        values:
        - event
  receivers:
    name: 
      - user1
```

**Comment by DesistDaydream** [comment]
This means that alerts can only be routed through additional labels?Manually adding Labels for those alerts seems inelegant.

From [here](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config) we can see, the webhook data structure pushed by AlertManager has a `.receiver` field. Can our Notification Manager use this field?

**Comment by benjaminhuo** [comment]
The receiver field can also be added to the received alerts labels, and then use route to specify the receiver label to route alerts

**Comment by DesistDaydream** [comment]
The `.receiver` field doesn't seem to be processed

alertmanager.yaml
```yaml
global:
  resolve_timeout: 5m
receivers:
  - name: "developer"
    webhook_configs:
      - url: "http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts"
  - name: "ops"
    webhook_configs:
      - url: "http://notification-manager-svc.kubesphere-monitoring-system.svc:19093/api/v2/alerts"
route:
  group_by:
    - job
  group_interval: 1m
  group_wait: 30s
  receiver: "ops"
  repeat_interval: 1m
  routes:
    - match:
        alertname: Watchdog
      receiver: "developer"
templates:
  - /etc/alertmanager/config-out/*.tmpl
```

Recevier
```yaml
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: developer-receiver
  labels:
    app: notification-manager
    type: tenant
    user: developer-receiver
spec:
  dingtalk:
    chatbot:
      atMobiles:
        - XXXX
      webhook:
        value: "https://oapi.dingtalk.com/robot/send?access_token=XXX"
    enabled: true
    template: '{{ template "nm.default.markdown" . }}'
    titleTemplate: '{{ template "nm.default.subject" . }}'
    tmplType: markdown
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
      key: "template.go.tmpl"
```

Router
```yaml
apiVersion: notification.kubesphere.io/v2beta2
kind: Router
metadata:
  name: developer-router
spec:
  alertSelector:
    matchExpressions:
      - key: receiver
        operator: In
        values:
          - developer
  receivers:
    name:
      - developer-receiver
````
