### ISSUE TITLE
sms receiver: Invalid value: "integer": spec.sms.phoneNumbers in body must be of type string: "integer"

### ISSUE THREAD

**Issue by Bennu-Li** [kubesphere/notification-manager#154]
I use the receiver.yaml as follows:
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-receiver
  labels:
    type: tenant
    user: admin
spec:
  sms:
    alertSelector:
      matchExpressions:
      - key: namespace
        operator: DoesNotExist
    smsConfigSelector:
      matchLabels:
        type: tenant
        user: admin
    enabled: true
    template: nm.default.text
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
    phoneNumbers:
      - 13612345678
```

And got this error:
```
The Receiver "global-receiver" is invalid: spec.sms.phoneNumbers: Invalid value: "integer": spec.sms.phoneNumbers in body must be of type string: "integer"
```
