### ISSUE TITLE
如何配置 a Receiver 接收的内容为英文, b Receiver 接受的内容为中文?

### ISSUE THREAD

**Issue by east4ming** [kubesphere/notification-manager#157]
我想配置 a Receiver 接收的内容为英文, b Receiver 接受的内容为中文.

目前看了文档, 只有 `NotificationManager` 中可以定义 `template.language`.
但是如何在 b Receiver 中定义 language 为中文?
试过这样不行:

```yaml
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-receiver
  labels:
    type: tenant
    user: admin
spec:
  email:
    ...
    template:
      language: zh-cn
    ...
```
