### ISSUE TITLE
send notification error" error="Secret \"feishu-config-secret\" not found"

### ISSUE THREAD

**Issue by Bennu-Li** [kubesphere/notification-manager#167]
I send notification to a feishu user with the following receiver:
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: receiver-test
  labels:
    type: global
spec:
  feishu:
    alertSelector:
      matchExpressions:
      - key: severity
        operator: In
        values:
          - critical
    feishuConfigSelector:
      matchLabels:
        type: default
    user:
      - 3e55xxxx
    enabled: true
    tmplType: text
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
```

And I get the following error logs from the pod `notification-manager-deployment-cd8b9b946-sshmp`
![image](https://user-images.githubusercontent.com/53458891/194828399-dfef6d2b-df7b-40c8-8fcf-270045229379.png)
