### ISSUE TITLE
配置通知渠道报错

### ISSUE THREAD

**Issue by Anoxia** [kubesphere/notification-manager#228]
## 问题描述：

使用以下配置后一直报错。

## 环境：

Kubesphere 版本：3.4.1
notification-manager-operator 镜像：kubesphere/notification-manager-operator:v2.3.0
Kubernetes 版本：v1.26.10-eks

## Receiver 配置

```yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: kubesphere-monitoring-system
  name: feishu-receiver-secret
type: Opaque
data:
  webhook: aHR0cHM6Ly9vcGVuLmZlaXNodS5jbi9vcGVuLWFwaXMvYm90L3YyL2hvb2svNzY1c3F3cXc3ODQtYWQzZTIwLTFjZTViOA==
  secret: TXZZbTkwTDNZeUwyaHZiMnN2TnpZMWMzRjNjWGMzT0RRdA==

---
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-receiver
  namespace: kubesphere-monitoring-system
  labels:
    type: global
spec:
  feishu:
    alertSelector:
      matchExpressions:
        - key: namespace
          operator: DoesNotExist
    chatbot:
      webhook:
        valueFrom:
          secretKeyRef:
            key: webhook
            name: feishu-receiver-secret
            namespace: kubesphere-monitoring-system
      keywords:
        - kubesphere
      secret:
        valueFrom:
          secretKeyRef:
            key: secret
            name: feishu-receiver-secret
            namespace: kubesphere-monitoring-system
    enabled: true
    template: nm.feishu.post
    tmplType: post
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system

```

## 错误输出：

```
notification-manager-operator 2023-11-22T19:48:33.884Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-notification-kubesp
here-io-v2beta2-receiver", "UID": "0c3c7a11-8314-4acf-9b1c-3c4be7d7c2a0", "kind": "notification.kubesphere.io/v2beta2, Kind=Receiver", "resource": {"group":"notificatio
n.kubesphere.io","version":"v2beta2","resource":"receivers"}}                                                                                                           
notification-manager-operator 2023-11-22T19:48:33.886Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-notification-kubesphe
re-io-v2beta2-receiver", "code": 200, "reason": "", "UID": "0c3c7a11-8314-4acf-9b1c-3c4be7d7c2a0", "allowed": true}                                                     
notification-manager-operator 2023/11/22 19:48:34 http: TLS handshake error from 10.0.150.252:50178: remote error: tls: bad certificate                                 
notification-manager-operator 2023/11/22 19:48:34 http: TLS handshake error from 10.0.130.212:39956: remote error: tls: bad certificate                                 
notification-manager-operator 2023/11/22 19:48:34 http: TLS handshake error from 10.0.130.212:39960: remote error: tls: bad certificate                                 
notification-manager-operator 2023/11/22 19:48:34 http: TLS handshake error from 10.0.150.252:50192: remote error: tls: bad certificate                                 
notification-manager-operator 2023/11/22 19:48:34 http: TLS handshake error from 10.0.130.212:39976: remote error: tls: bad certificate
```
