### ISSUE TITLE
helm升级到2.5.1 报错

### ISSUE THREAD

**Issue by wadeLouis** [kubesphere/notification-manager#274]
命令：
```shell
helm upgrade notification-manager   --set kubesphere.enabled=true --set notificationmanager.sidecar.tenant.resources.limits.cpu=500m --set notificationmanager.sidecar.tenant.resources.limits.memory=500Mi --set notificationmanager.sidecar.tenant.resources.requests.cpu=500m --set notificationmanager.sidecar.tenant.resources.requests.memory=500Mi --set operator.containers.proxy.image.repo=harbor-k8s.healthan.net/kubesphere/kube-rbac-proxy --set operator.containers.operator.image.repo=harbor-k8s.healthan.net/kubesphere/notification-manager-operator  --set notificationmanager.image.repo=harbor-k8s.healthan.net/kubesphere/notification-manager --set notificationmanager.sidecar.image.repo=harbor-k8s.healthan.net/kubesphere/notification-tenant-sidecar   -n kubesphere-monitoring-system  ./notification-manager.tgz


```
错误：
```shell
Error: UPGRADE FAILED: cannot patch "notification-manager" with kind NotificationManager: NotificationManager.notification.kubesphere.io "notification-manager" is invalid: [spec.sidecars.tenant.name: Required value, spec.sidecars.tenant.type: Required value]
```

**Comment by wanjunlei** [comment]
sidecar => sidecars

**Comment by wadeLouis** [comment]
还是没明白，values 里面定义的就是sidecar，notificationmanager.yaml引用的也是sidecar，报错的信息是spec.sidecars.tenant.name需要这个值。notificationmanager.yaml中这一段已经定义了
```yaml
  {{- if .Values.kubesphere.enabled }}
  sidecars:
    tenant:
  {{- if .Values.kubesphere.image }}
      image: {{ include "global.imageRegistry" . }}{{ .Values.kubesphere.image }}
  {{- else }}
      image: {{ include "global.imageRegistry" . }}{{ .Values.notificationmanager.sidecar.image.repo }}:{{ .Values.kubesphere.version }}
  {{- end }}
      name: tenant
      type: kubesphere
      resources:
        limits:
          cpu: {{ .Values.notificationmanager.sidecar.tenant.resources.limits.cpu }}
          memory: {{ .Values.notificationmanager.sidecar.tenant.resources.limits.memory }}
        requests:
          cpu: {{  .Values.notificationmanager.sidecar.tenant.resources.requests.cpu }}
          memory: {{  .Values.notificationmanager.sidecar.tenant.resources.requests.memory }}
  {{- end }}
```
helm   dry-run 的结果部分内容：
```yaml
  sidecars:
    tenant:
      image: harbor-k8s.net/kubesphere/notification-tenant-sidecar:v3.2.0
      name: tenant
      type: kubesphere
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
```
