### ISSUE TITLE
notifycation-manager没有把告警消息转发到飞书群

### ISSUE THREAD

**Issue by SsLaLal** [kubesphere/notification-manager#275]
`Receiver`
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-receiver
  labels:
    type: global
    user: admin
  namespace: kubesphere-monitoring-federated
spec:
  feishu:
    chatbot:
      webhook:
        valueFrom:
          secretKeyRef:
            key: webhook
            name: global-receiver-secret
            namespace: kubesphere-monitoring-federated
    template: '{{ template "nm.feishu.text" . }}'
    tmplType: text
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
```

`Secret`
```
apiVersion: v1
kind: Secret
metadata:
  name: global-receiver-secret
  namespace: kubesphere-monitoring-federated
type: Opaque
data:
  webhook: "{{aaaaaaaaaaaaaaaaa}}" # 这里需替换为实际飞书Webhook地址的Base64编码值
  secret: "{{aaaaaaaaaaaaaaaaa}}" # 这里需替换为实际secret值的Base64编码值
```

`nm`
```
apiVersion: notification.kubesphere.io/v2beta1
kind: NotificationManager
metadata:
  annotations:
    meta.helm.sh/release-name: notification-manager
    meta.helm.sh/release-namespace: kubesphere-monitoring-system
  labels:
    app: notification-manager
    app.kubernetes.io/managed-by: Helm
  name: notification-manager
spec:
  affinity: {}
  defaultConfigSelector:
    matchLabels:
      type: default
  defaultSecretNamespace: kubesphere-monitoring-federated
  image: 'kubesphere/notification-manager:v2.3.0'
  imagePullPolicy: IfNotPresent
  nodeSelector: {}
  portName: webhook
  receivers:
    globalReceiverSelector:
      matchLabels:
        type: global
    options:
      email:
        deliveryType: bulk
        notificationTimeout: 5
      global:
        cluster: {{aaaaaaa}}
      slack:
        notificationTimeout: 5
      wechat:
        notificationTimeout: 5
    tenantKey: user
    tenantReceiverSelector:
      matchLabels:
        type: tenant
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 5m
      memory: 20Mi
  serviceAccountName: notification-manager-sa
  tolerations: []
  volumeMounts: []
  volumes: []
```
`
然后nm-deployment的日志是这样的
`
```
 level=error ts=2024-12-02T07:04:44.594071853Z caller=feishu.go:147 msg="FeishuNotifier: generate message error" error="template: :1:12: executing \"\" at <{{template \"nm.feishu.texts\" .}}>: template \"nm.feishu.texts\" not defined"

 level=error ts=2024-12-02T07:04:44.594091392Z caller=feishu.go:147 msg="FeishuNotifier: generate message error" error="template: :1:12: executing \"\" at <{{template \"nm.feishu.texts\" .}}>: template \"nm.feishu.texts\" not defined"

 level=error ts=2024-12-02T07:04:44.594189215Z caller=dispatcher.go:128 msg="Dispatcher: process alerts failed" seq=1557
 level=info ts=2024-12-02T07:04:53.172255424Z caller=controller.go:537 msg="Receiver changed" op=update name=global-receiver
```
alertmanager中告警是存在的，但是通知一直没有发布到飞书群的机器人里，需要从哪里排查问题

**Comment by SsLaLal** [comment]
![image](https://github.com/user-attachments/assets/a51f9a4f-91dd-4f1a-943a-87ea65f57678)
![image](https://github.com/user-attachments/assets/009a4cb3-4036-47ca-91db-f1764990f4fc)
另外想知道这个地方配置的通知渠道为什么也没有收到通知

**Comment by SsLaLal** [comment]
```

```

**Comment by SsLaLal** [comment]
> > 已解决
> 
> 什么问题

能转发的，我吧所有Receiver和Config的cr删了重建，现在想想可能是配置url的base64有问题
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-feishu-receiver
  labels:
    type: global
    user: admin
  namespace: kubesphere-monitoring-federated
spec:
  feishu:
    chatbot:
      webhook:
        valueFrom:
          secretKeyRef:
            key: webhook
            name: global-receiver-secret
            namespace: kubesphere-monitoring-federated
    template: '{{ template "nm.feishu.text" . }}'
    tmplType: text
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
```

```
apiVersion: v1
kind: Secret
metadata:
  name: global-receiver-secret
  namespace: kubesphere-monitoring-federated
type: Opaque
data:
  webhook: "" # 这里需替换为实际飞书Webhook地址的Base64编码值
  secret: "" # 这里需替换为实际secret值的Base64编码值
```

```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-webhook-receiver
  labels:
    type: global
    user: admin
spec:
  webhook:
    alertSelector:
      matchExpressions:
        - key: namespace
          operator: DoesNotExist
    enabled: true
    template: '{{ template "webhook.default.message" . }}'
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
    url: "http://${domain}/api/kwatch/alert"
    #service: []
    httpConfig: 
      tlsConfig: 
        insecureSkipVerify: true
```
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-email-receiver
  labels:
    type: global
    user: admin
spec:
  email:
    enabled: true
    template: '{{ template "nm.default.html" . }}'
    subjectTemplate: '{{ template "nm.default.subject" .}}'
    tmplType: html
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
    to:
    - @gmail.com
    - @gmail.com
```
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Config
metadata:
  name: default-email-config
  namespace: kubesphere-monitoring-federated
  labels:
    type: default
spec:
  email:
    hello: "hello"
    authIdentify: ""
    authPassword:
      value: "应用专用密码"
    authUsername: @gmail.com
    from: @gmail.com
    requireTLS: true
    smartHost:
      host: smtp.gmail.com
      port: 587
    tls: {}
```
